package com.example.projectadd

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.google.firebase.firestore.FirebaseFirestore

class MedicineDataActivity : AppCompatActivity() {
    private lateinit var firestore: FirebaseFirestore

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_medicine_data)

        // Initialize Firestore
        firestore = FirebaseFirestore.getInstance()

        val recyclerView: RecyclerView = findViewById(R.id.recyclerView) // Initialize RecyclerView

        val arrContact = ArrayList<ContactModel>()
        arrContact.add(ContactModel("abhayarishta","10","1"))
        arrContact.add(ContactModel("amritarishta","10","1"))
        arrContact.add(ContactModel("aragvadharishta","10","1"))
        arrContact.add(ContactModel("aravindasava","10","1"))
        arrContact.add(ContactModel("arjunarishta/parthadyarishta","10","1"))
        arrContact.add(ContactModel("ashokarishta","10","1"))
        arrContact.add(ContactModel("ashvagandharishta","10","1"))
        arrContact.add(ContactModel("balarishta","10","1"))
        arrContact.add(ContactModel("chandanasava","10","1"))
        arrContact.add(ContactModel("dashamularishta","10","1"))
        arrContact.add(ContactModel("drakshasava","10","1"))
        arrContact.add(ContactModel("draksharishta","10","1"))
        arrContact.add(ContactModel("jirakadyarishta","10","1"))
        arrContact.add(ContactModel("kanakasava","10","1"))
        arrContact.add(ContactModel("kumaryasava","10","1"))
        arrContact.add(ContactModel("kutajarishta","10","1"))
        arrContact.add(ContactModel("khadirarishta","10","1"))
        arrContact.add(ContactModel("lodhrasava/rodhrasava","10","1"))
        arrContact.add(ContactModel("lohasava","10","1"))
        arrContact.add(ContactModel("mustakarishta","10","1"))
        arrContact.add(ContactModel("pippalyadyasava","10","1"))
        arrContact.add(ContactModel("rohitakarishta","10","1"))
        arrContact.add(ContactModel("sarasvatarishta","10","1"))
        arrContact.add(ContactModel("ushirasava","10","1"))
        arrContact.add(ContactModel("vasakasava","10","1"))
        arrContact.add(ContactModel("punarnavasava","10","1"))
        arrContact.add(ContactModel("arka yavani/arka ajvayana","10","1"))
        arrContact.add(ContactModel("arka shatpushpa/mishr eyarka","10","1"))
        arrContact.add(ContactModel("arka pudina","10","1"))
        arrContact.add(ContactModel("agastya haritaki/agastya rasayana","10","1"))
        arrContact.add(ContactModel("bilvadi leha","10","1"))
        arrContact.add(ContactModel("brahama rasayana","10","1"))
        arrContact.add(ContactModel("chitraka haritaki","10","1"))
        arrContact.add(ContactModel("chyavanprash avaleha","10","1"))
        arrContact.add(ContactModel("drakshavaleha","10","1"))
        arrContact.add(ContactModel("haridrakhanda paka","10","1"))
        arrContact.add(ContactModel("kutajavaleha","10","1"))
        arrContact.add(ContactModel("kalyanak guda","10","1"))
        arrContact.add(ContactModel("kantakaryavaleha","10","1"))
        arrContact.add(ContactModel("kushmandaka rasayana","10","1"))
        arrContact.add(ContactModel("puga khanda/supari paka","10","1"))
        arrContact.add(ContactModel("saubhagyashunthi paka","10","1"))
        arrContact.add(ContactModel("shatavariguda","10","1"))
        arrContact.add(ContactModel("vasavaleha","10","1"))
        arrContact.add(ContactModel("vyaghri haritaki","10","1"))
        arrContact.add(ContactModel("dashamula kvatha churna","10","1"))
        arrContact.add(ContactModel("dashamula katutraya kvatha churna","10","1"))
        arrContact.add(ContactModel("dhanyapanchaka kashaya churna","10","1"))
        arrContact.add(ContactModel("guduchyadi kashaya churna","10","1"))
        arrContact.add(ContactModel("indukantam kashayam churna","10","1"))
        arrContact.add(ContactModel("pancha-valkala kashaya churna","10","1"))
        arrContact.add(ContactModel("pathyadi kvatha(shadanga) churna","10","1"))
        arrContact.add(ContactModel("phalatrikadi kvatha churna","10","1"))
        arrContact.add(ContactModel("rasnasaptaka kashaya churna","10","1"))
        arrContact.add(ContactModel("shadanga kvatha churna","10","1"))
        arrContact.add(ContactModel("trinapanchamula kvatha churna","10","1"))
        arrContact.add(ContactModel("varunadi kvatha churna","10","1"))
        arrContact.add(ContactModel("vasaguduchyadi kashaya churna","10","1"))
        arrContact.add(ContactModel("amritadi guggulu","10","1"))
        arrContact.add(ContactModel("gokshuradi guggulu","10","1"))
        arrContact.add(ContactModel("kanchanara guggulu","10","1"))
        arrContact.add(ContactModel("kaishora guggulu","10","1"))
        arrContact.add(ContactModel("lakshadi guggulu","10","1"))
        arrContact.add(ContactModel("navak guggulu","10","1"))
        arrContact.add(ContactModel("rasna guggulu","10","1"))
        arrContact.add(ContactModel("simhanada guggulu","10","1"))
        arrContact.add(ContactModel("saptavinshati guggulu","10","1"))
        arrContact.add(ContactModel("triphala guggulu","10","1"))
        arrContact.add(ContactModel("trayodashanga guggulu","10","1"))
        arrContact.add(ContactModel("punarnava guggulu","10","1"))
        arrContact.add(ContactModel("yogaraja guggulu","10","1"))
        arrContact.add(ContactModel("brahmi ghrita","10","1"))
        arrContact.add(ContactModel("dadimadi ghrita","10","1"))
        arrContact.add(ContactModel("guggulutiktaka ghrita","10","1"))
        arrContact.add(ContactModel("jathyadi ghrita","10","1"))
        arrContact.add(ContactModel("kalyanaka ghrita","10","1"))
        arrContact.add(ContactModel("kshirashatpala ghrita","10","1"))
        arrContact.add(ContactModel("panchatikta ghrita","10","1"))
        arrContact.add(ContactModel("phala ghrita","10","1"))
        arrContact.add(ContactModel("shatavaryadi ghrita","10","1"))
        arrContact.add(ContactModel("sukumar ghrita","10","1"))
        arrContact.add(ContactModel("indu kanta ghrita","10","1"))
        arrContact.add(ContactModel("tiktaka ghrita","10","1"))
        arrContact.add(ContactModel("triphala ghrita","10","1"))
        arrContact.add(ContactModel("ajamodadi churna","10","1"))
        arrContact.add(ContactModel("avipattikara churna","10","1"))
        arrContact.add(ContactModel("balachaturbhadra churna","10","1"))
        arrContact.add(ContactModel("bilvadi churna","10","1"))
        arrContact.add(ContactModel("dadimastak churna","10","1"))
        arrContact.add(ContactModel("dashanasanskara churna","10","1"))
        arrContact.add(ContactModel("eladi churna","10","1"))
        arrContact.add(ContactModel("hingvashtaka churna","10","1"))
        arrContact.add(ContactModel("lavanabhaskara churna/bhaskarlavan churna","10","1"))
        arrContact.add(ContactModel("nisha-amalaki churna","10","1"))
        arrContact.add(ContactModel("pushyanuga churna","10","1"))
        arrContact.add(ContactModel("panchanimba churna","10","1"))
        arrContact.add(ContactModel("sitopaladi churna","10","1"))
        arrContact.add(ContactModel("talishadya churna","10","1"))
        arrContact.add(ContactModel("trikatu churna","10","1"))
        arrContact.add(ContactModel("triphala churna","10","1"))
        arrContact.add(ContactModel("jatiphaladya churna","10","1"))
        arrContact.add(ContactModel("amalaki churna","10","1"))
        arrContact.add(ContactModel("arjuna churna","10","1"))
        arrContact.add(ContactModel("ashvagandha churna","10","1"))
        arrContact.add(ContactModel("gukshura churna","10","1"))
        arrContact.add(ContactModel("guduchi churna","10","1"))
        arrContact.add(ContactModel("haritaki churna","10","1"))
        arrContact.add(ContactModel("pipali churna","10","1"))
        arrContact.add(ContactModel("pipali mula churna","10","1"))
        arrContact.add(ContactModel("punarnava churna","10","1"))
        arrContact.add(ContactModel("shunti churna","10","1"))
        arrContact.add(ContactModel("sarasvata churna","10","1"))
        arrContact.add(ContactModel("trivita churna","10","1"))
        arrContact.add(ContactModel("vidanga churna","10","1"))
        arrContact.add(ContactModel("yashti/yashtimadhu/madhuyasti churna","10","1"))
        arrContact.add(ContactModel("Anutaila","10","1"))
        arrContact.add(ContactModel("Aparmargkshara","10","1"))
        arrContact.add(ContactModel("Bala Taila","10","1"))
        arrContact.add(ContactModel("Balashvagandha taila","10","1"))
        arrContact.add(ContactModel("Dhanvantar taila/ Dhanvantar taila avarti","10","1"))
        arrContact.add(ContactModel("Eranda taila","10","1"))
        arrContact.add(ContactModel("Erimedadi taita","10","1"))
        arrContact.add(ContactModel("Gandharvashtha taila","10","1"))
        arrContact.add(ContactModel("Jatyadi taila","10","1"))
        arrContact.add(ContactModel("Kashirbala taila/ Kashirbala taila Avarti","10","1"))
        arrContact.add(ContactModel("Kottamachukkadi taila","10","1"))
        arrContact.add(ContactModel("Karpuradi Taila","10","1"))
        arrContact.add(ContactModel("Kasisadi taila","10","1"))
        arrContact.add(ContactModel("laghuvishagarbha taila","10","1"))
        arrContact.add(ContactModel("marichyadi taila","10","1"))
        arrContact.add(ContactModel("Mahanaryan taila","10","1"))
        arrContact.add(ContactModel("Mahamas taila","10","1"))
        arrContact.add(ContactModel("Murivenna taila","10","1"))
        arrContact.add(ContactModel("Narayna taila","10","1"))
        arrContact.add(ContactModel("Nalpamaradi taila","10","1"))
        arrContact.add(ContactModel("Nargundi taila","10","1"))
        arrContact.add(ContactModel("Panchaguna taila","10","1"))
        arrContact.add(ContactModel("pinda taila","10","1"))
        arrContact.add(ContactModel("prasarini taila","10","1"))
        arrContact.add(ContactModel("sahacharadi taila/Brihatsacharadi","10","1"))
        arrContact.add(ContactModel("saindhavadi taila","10","1"))
        arrContact.add(ContactModel("Shadabindu taila","10","1"))
        arrContact.add(ContactModel("Somaraji/ Bakuchi taila","10","1"))
        arrContact.add(ContactModel("Apamarga kshar","10","1"))
        arrContact.add(ContactModel("Yvakshar","10","1"))
        arrContact.add(ContactModel("Ksharshutra","10","1"))
        arrContact.add(ContactModel("Dashanga lepa","10","1"))
        arrContact.add(ContactModel("sweta Malaham","10","1"))
        arrContact.add(ContactModel("sarjarasa Malahara","10","1"))
        arrContact.add(ContactModel("abhayadimodakam","10","1"))
        arrContact.add(ContactModel("bilvadi gutika","10","1"))
        arrContact.add(ContactModel("chandraprabha vati","10","1"))
        arrContact.add(ContactModel("Chitrakadi Gutika","10","1"))
        arrContact.add(ContactModel("Dhanvantar Gutika","10","1"))
        arrContact.add(ContactModel("Eladi Gutika","10","1"))
        arrContact.add(ContactModel("Kankayan Gutika","10","1"))
        arrContact.add(ContactModel("khadiradi Gutika(mukhroga)","10","1"))
        arrContact.add(ContactModel("Kutajaghan Vati","10","1"))
        arrContact.add(ContactModel("lavangati vati","10","1"))
        arrContact.add(ContactModel("lahsunadi vati","10","1"))
        arrContact.add(ContactModel("prabhakara vati","10","1"))
        arrContact.add(ContactModel("rajahpravartini vati","10","1"))
        arrContact.add(ContactModel("samshamini vati","10","1"))
        arrContact.add(ContactModel("sarpagandhagana vati","10","1"))
        arrContact.add(ContactModel("sanjivani vati","10","1"))
        arrContact.add(ContactModel("vettumaran gutika","10","1"))
        arrContact.add(ContactModel("elanirkuzambu","10","1"))
        arrContact.add(ContactModel("guduchi sattva ","10","1"))
        arrContact.add(ContactModel("panchamrita parpati","10","1"))
        arrContact.add(ContactModel("shweta parpati","10","1"))
        arrContact.add(ContactModel("akika pishti","10","1"))
        arrContact.add(ContactModel("mukta pishti","10","1"))
        arrContact.add(ContactModel("pravala pishti","10","1"))
        arrContact.add(ContactModel("godanti bhasma","10","1"))
        arrContact.add(ContactModel("jaharamohara bhasma","10","1"))
        arrContact.add(ContactModel("kapardika bhasma","10","1"))
        arrContact.add(ContactModel("mandur bhasma","10","1"))
        arrContact.add(ContactModel("muktashukti bhasma","10","1"))
        arrContact.add(ContactModel("shankha bhasma","10","1"))
        arrContact.add(ContactModel("sphatika bhasma","10","1"))
        arrContact.add(ContactModel("tankana bhasma","10","1"))
        arrContact.add(ContactModel("punarnavadi mandura","10","1"))
        arrContact.add(ContactModel("arogyavardhini vati","10","1"))
        arrContact.add(ContactModel("arsho kuthara rasa","10","1"))
        arrContact.add(ContactModel("brahmi vati","10","1"))
        arrContact.add(ContactModel("gandhak rasayana","10","1"))
        arrContact.add(ContactModel("kamadudha rasa","10","1"))
        arrContact.add(ContactModel("laghumalini vasaranta rasa","10","1"))
        arrContact.add(ContactModel("laghu sutashekhara rasa","10","1"))
        arrContact.add(ContactModel("navajeevana rasa","10","1"))
        arrContact.add(ContactModel("shankha vati","10","1"))
        arrContact.add(ContactModel("shirahshuladi vajra rasa","10","1"))
        arrContact.add(ContactModel("shavasakuthara rasa","10","1"))
        arrContact.add(ContactModel("smritisagra rasa","10","1"))
        arrContact.add(ContactModel("tribhuvankirti rasa","10","1"))
        arrContact.add(ContactModel("vatankushagajan rasa","10","1"))
        arrContact.add(ContactModel("vatavidhavansan rasa","10","1"))
        arrContact.add(ContactModel("navayasa lauha","10","1"))
        arrContact.add(ContactModel("saptamrita lauha","10","1"))
        arrContact.add(ContactModel("Majoon-e-Ispand Sokhtani","10","1"))
        arrContact.add(ContactModel("Majoon-e-Jograj Guggal","10","1"))
        arrContact.add(ContactModel("Majoon-e-Kundur","10","1"))
        arrContact.add(ContactModel("Majoon-e-Masik-ul-Baul","10","1"))
        arrContact.add(ContactModel("Majoon-e-Muqawwi-erahem","10","1"))
        arrContact.add(ContactModel("Majoon-e-Muqil","10","1"))
        arrContact.add(ContactModel("Majoon-e-Najah","10","1"))
        arrContact.add(ContactModel("Majoon-e-Piyaz","10","1"))
        arrContact.add(ContactModel("Majoon-e-Sangdana-e-Murgh","10","1"))
        arrContact.add(ContactModel("Majoon-e-Seer Alvi Khani","10","1"))
        arrContact.add(ContactModel("Majoon-e-Suhag Sonth","10","1"))
        arrContact.add(ContactModel("Majoon-e-SupariPak","10","1"))
        arrContact.add(ContactModel("Majoon-e-Suranjan","10","1"))
        arrContact.add(ContactModel("Majoon-e-Ushba","10","1"))
        arrContact.add(ContactModel("Mufarreh Barid","10","1"))
        arrContact.add(ContactModel("Murabba Amla","10","1"))
        arrContact.add(ContactModel("Raughan-e-Aamla","10","1"))
        arrContact.add(ContactModel("Raughan-e-Badam Shirin","10","1"))
        arrContact.add(ContactModel("Raughan-e-Baiza-e-Murgh","10","1"))
        arrContact.add(ContactModel("Raughan-e-Gul","10","1"))
        arrContact.add(ContactModel("Raughan-e-Ikseer","10","1"))
        arrContact.add(ContactModel("Raughan-e-Kahu","10","1"))
        arrContact.add(ContactModel("Raughan-e-Laboob Saba","10","1"))
        arrContact.add(ContactModel("Raughan-e-Malkangni","10","1"))
        arrContact.add(ContactModel("Raughan-e-Qaranfal","10","1"))
        arrContact.add(ContactModel("Raughan-e-Suranjan","10","1"))
        arrContact.add(ContactModel("Raughan-e-Surkh","10","1"))
        arrContact.add(ContactModel("Raughan-e-Turb","10","1"))
        arrContact.add(ContactModel("Raughan-e-Zaitoon","10","1"))
        arrContact.add(ContactModel("Sufoof-e-Bars","10","1"))
        arrContact.add(ContactModel("Sufoof-e-Chobchini","10","1"))
        arrContact.add(ContactModel("Sufoof-e-Chutki","10","1"))
        arrContact.add(ContactModel("Sufoof-e-Habis-ud-Dam","10","1"))
        arrContact.add(ContactModel("Sufoof-e-Hazim","10","1"))
        arrContact.add(ContactModel("Sufoof-e-Hijrul Yahud","10","1"))
        arrContact.add(ContactModel("Sufoof-e-Mudrr-e-Haiz","10","1"))
        arrContact.add(ContactModel("Sufoof-e-Muhazzil","10","1"))
        arrContact.add(ContactModel("Sufoof-e-Namak-e-Shaikhur Raees","10","1"))
        arrContact.add(ContactModel("Sufoof-e-Suranjan","10","1"))
        arrContact.add(ContactModel("Sufoof-e-Teen","10","1"))
        arrContact.add(ContactModel("Sharbat-e-Anjbar","10","1"))
        arrContact.add(ContactModel("Sharbat-e-Belgiri","10","1"))
        arrContact.add(ContactModel("Sharbat-e-Buzoori Motadil","10","1"))
        arrContact.add(ContactModel("Sharbat-e-Deenar","10","1"))
        arrContact.add(ContactModel("Sharbat-e-Ejaz","10","1"))
        arrContact.add(ContactModel("Sharbat-e-Faulad","10","1"))
        arrContact.add(ContactModel("Sharbat-e-Khaksi","10","1"))
        arrContact.add(ContactModel("Sharbat-e-Sadar","10","1"))
        arrContact.add(ContactModel("Sharbat-e-Toot Siyah","10","1"))
        arrContact.add(ContactModel("Sharbat-e-Unnab","10","1"))
        arrContact.add(ContactModel("Banadiq-ul-Bazoor","10","1"))
        arrContact.add(ContactModel("Dawa-ul-Kurkum","10","1"))
        arrContact.add(ContactModel("Dawa-ul-Misk Motadil Sada","10","1"))
        arrContact.add(ContactModel("Halwa-e-Ghekawar","10","1"))
        arrContact.add(ContactModel("Malerian","10","1"))
        arrContact.add(ContactModel("Qutor-e-Ramad Qawi","10","1"))
        arrContact.add(ContactModel("Sunoon-e-Mukhrij-e-Rutubat","10","1"))
        arrContact.add(ContactModel("Tiryaq-e-Arba","10","1"))
        arrContact.add(ContactModel("Tiryaq-e-Nazla","10","1"))
        arrContact.add(ContactModel("Zuroor-e-Kath","10","1"))
        arrContact.add(ContactModel("Zuroor-e-Qula","10","1"))
        arrContact.add(ContactModel("Aamla","10","1"))
        arrContact.add(ContactModel("Afsanteen","10","1"))
        arrContact.add(ContactModel("Anjeer","10","1"))
        arrContact.add(ContactModel("Arjun","10","1"))
        arrContact.add(ContactModel("Asl-us-Soos","10","1"))
        arrContact.add(ContactModel("Aspaghol","10","1"))
        arrContact.add(ContactModel("Babchi","10","1"))
        arrContact.add(ContactModel("Badiyan","10","1"))
        arrContact.add(ContactModel("Banafsha","10","1"))
        arrContact.add(ContactModel("Bisfayej","10","1"))
        arrContact.add(ContactModel("Burada Sandal Surkh","10","1"))
        arrContact.add(ContactModel("Burada Sandal Safaid","10","1"))
        arrContact.add(ContactModel("Burada Sheesham","10","1"))
        arrContact.add(ContactModel("Chiraita","10","1"))
        arrContact.add(ContactModel("Chobchini","10","1"))
        arrContact.add(ContactModel("Gilo","10","1"))
        arrContact.add(ContactModel("Gaozaban","10","1"))
        arrContact.add(ContactModel("Ghafis","10","1"))
        arrContact.add(ContactModel("GulTesu","10","1"))
        arrContact.add(ContactModel("Gul-e-Surkh","10","1"))
        arrContact.add(ContactModel("Gul-e-Babuna","10","1"))
        arrContact.add(ContactModel("Gul-e-Banafsha","10","1"))
        arrContact.add(ContactModel("Khar-e-Khasak Khurd","10","1"))
        arrContact.add(ContactModel("Khiyar Shambar","10","1"))
        arrContact.add(ContactModel("Khurfa","10","1"))
        arrContact.add(ContactModel("Khaksi","10","1"))
        arrContact.add(ContactModel("Khubbazi","10","1"))
        arrContact.add(ContactModel("Konch","10","1"))
        arrContact.add(ContactModel("Mako","10","1"))
        arrContact.add(ContactModel("Mundi","10","1"))
        arrContact.add(ContactModel("Neelofar","10","1"))
        arrContact.add(ContactModel("Revandchini","10","1"))
        arrContact.add(ContactModel("Sana","10","1"))
        arrContact.add(ContactModel("Satawar","10","1"))
        arrContact.add(ContactModel("Shahatra","10","1"))
        arrContact.add(ContactModel("Sumbul-ut-Teeb","10","1"))
        arrContact.add(ContactModel("Tukhm-e-Kasni","10","1"))
        arrContact.add(ContactModel("Tukhm-e-Khatmi","10","1"))
        arrContact.add(ContactModel("Tukhm-e-Karafs","10","1"))
        arrContact.add(ContactModel("Zufa Yabis","10","1"))

        recyclerView.layoutManager = LinearLayoutManager(this)
        // Set layout manager
        val recyclerAdapter = RecyclerContactAdapter(this, arrContact)
        recyclerView.adapter = recyclerAdapter

        // Upload data to Firestore
        uploadDataToFirestore(arrContact)
    }
    private fun uploadDataToFirestore(arrContact: ArrayList<ContactModel>) {
        val collectionRef = firestore.collection("contacts")

        for (contact in arrContact) {
            collectionRef.add(contact)
                .addOnSuccessListener { documentReference ->
                    println("DocumentSnapshot added with ID: ${documentReference.id}")
                }
                .addOnFailureListener { e ->
                    println("Error adding document: $e")
                }
        }
    }
}
